### ISSUE TITLE
Theme request: arduino-dark

### ISSUE THREAD

**Issue by BelKed** [yusanshi/embed_like_gist#11]
Hey yusnanshi,

I would like to request to add _Arduino dark theme_ based on _One Dark Pro_ – https://github.com/konrad91/OneDarkArduino.
It's really nice theme for highlighting Arduino code.

Here is sample image of code highlighted by that theme:
![Arduino dark theme](https://user-images.githubusercontent.com/66956532/105686996-36400e00-5ef8-11eb-81eb-e45796482ece.png)

**Comment by yusanshi** [comment]
Thanks for your idea.

As you know, the code highlighting job in the repo is provided by [highlight.js](https://github.com/highlightjs/highlight.js/) and we're using the theme from it.

https://github.com/yusanshi/embed-like-gist/blob/master/embed.js#L33
![image](https://user-images.githubusercontent.com/36265606/105688300-61485300-5f34-11eb-832a-7e61c9e6e71a.png)


I just looked into <https://highlightjs.org/static/demo/>, and I found there is no Arduino Dark theme, but Arduino Light.
![image](https://user-images.githubusercontent.com/36265606/105688068-20e8d500-5f34-11eb-882b-78265ddb0099.png)


I checked the <https://github.com/konrad91/OneDarkArduino> repo you provided, and surely the code in it can't be directly used by this project. The needed style code should be like this:

https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/arduino-light.min.css
```css
.hljs{display:block;overflow-x:auto;padding:.5em;background:#FFFFFF}.hljs,.hljs-subst{color:#434f54}.hljs-keyword,.hljs-attribute,.hljs-selector-tag,.hljs-doctag,.hljs-name{color:#00979D}.hljs-built_in,.hljs-literal,.hljs-bullet,.hljs-code,.hljs-addition{color:#D35400}.hljs-regexp,.hljs-symbol,.hljs-variable,.hljs-template-variable,.hljs-link,.hljs-selector-attr,.hljs-selector-pseudo{color:#00979D}.hljs-type,.hljs-string,.hljs-selector-id,.hljs-selector-class,.hljs-quote,.hljs-template-tag,.hljs-deletion{color:#005C5F}.hljs-title,.hljs-section{color:#880000;font-weight:bold}.hljs-comment{color:rgba(149,165,166,0.8)}.hljs-meta-keyword{color:#728E00}.hljs-meta{color:#434f54}.hljs-emphasis{font-style:italic}.hljs-strong{font-weight:bold}.hljs-function{color:#728E00}.hljs-number{color:#8A7B52}
```


So I think there're 2 options we can choose from:
1. Write our own CSS code for Arduino Dark.
2. Request this theme to [highlight.js](https://github.com/highlightjs/highlight.js/). Since they have provided Arduino Light theme, adding a dark version should not be so hard, I think.  :)
